spring.application.name=fintech-service

//H2-InMemory-Database
spring.datasource.url=jdbc:h2:mem:financedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=fintech
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

//SECURITY
jwt.secret=my-super-secret-key-that-is-long-enough
jwt.expiration=3600000

# Logging Configuration

# Log levels
logging.level.root=WARN
logging.level.com.fintech.fintech_service=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# Log format in console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Write logs to file
logging.file.name=logs/fintech-service.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Max log file size before rolling
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7