spring.application.name=fintech-service

//H2-InMemory-Database
spring.datasource.url=jdbc:h2:mem:financedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=fintech
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

//SECURITY
jwt.secret=my-super-secret-key-that-is-long-enough
jwt.expiration=3600000